// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY } from '@/lib/env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Both were previously left to the library default, which has changed between
    // supabase-js releases — an upgrade could silently switch the OAuth flow. PKCE
    // keeps tokens out of the URL fragment; detectSessionInUrl is what completes the
    // Google sign-in redirect at /auth/callback.
    flowType: "pkce",
    detectSessionInUrl: true,
  },
});